FROM node:14.16.0
EXPOSE 8000
RUN npm install --quiet -g gatsby-cli
WORKDIR /app
COPY ./package.json ./package-lock.json ./
RUN npm i --package-lock-only
RUN npm ci
COPY . .
RUN gatsby clean
CMD ["gatsby", "develop", "-H", "0.0.0.0" ]