FROM cimg/node:12.13.1-browsers
EXPOSE 8000
#RUN npm install --quiet -g gatsby-cli@2.19.3
WORKDIR /app
COPY ./package.json .
#RUN npm install
COPY . .
#RUN gatsby clean
#CMD ["gatsby", "develop", "-H", "0.0.0.0" ]