DROP TABLE IF EXISTS commodity;
CREATE TABLE  IF NOT EXISTS
commodity(
  commodity_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  mineral_lease_type varchar(255)NOT NULL DEFAULT '' , 
  commodity varchar(255) NOT NULL DEFAULT '' ,  	   
  product varchar(255) NOT NULL DEFAULT '' , 		   
  commodity_order varchar(5) NOT NULL DEFAULT '',
  UNIQUE(mineral_lease_type,commodity, product)
)
