drop table if exists fund;
create table fund (
  fund_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  recipient varchar(255) NOT NULL DEFAULT '' ,
  fund_class varchar(255) NOT NULL DEFAULT '',  
  fund_type varchar(255) NOT NULL DEFAULT '',
  disbursemnt_type  varchar(255) NOT NULL DEFAULT '',
  revenue_type varchar(255) NOT NULL DEFAULT '', 
  source varchar(255) NOT NULL DEFAULT '',
  UNIQUE(recipient,fund_class,fund_type, revenue_type, source)
)
