DROP TABLE IF EXISTS period;
CREATE TABLE  IF NOT EXISTS period(
  period_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  period varchar(255) DEFAULT 'Monthly',
  calendar_year integer NOT NULL,
  fiscal_year integer  NOT NULL, 
  month integer NOT NULL, 
  month_long varchar(255) NOT NULL,
   month_short varchar(3) NOT NULL,	
  fiscal_month integer NOT NULL, 
  period_date date NOT NULL,
  UNIQUE(period,calendar_year,fiscal_year,month, month_long,fiscal_month, period_date)
)

