drop table if exists source;
create table source (
   location_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
   location_name varchar(255) NOT NULL DEFAULT '',
   fips_code  varchar(5) NOT NULL DEFAULT '', 
   state varchar(255) NOT NULL DEFAULT '',
   state_name varchar(255) NOT NULL DEFAULT '',  
   county varchar(255) NOT NULL DEFAULT '',  
   land_class varchar(255) NOT NULL DEFAULT '',
   land_category varchar(255) NOT NULL DEFAULT '' , 
   land_type varchar(255) NOT NULL DEFAULT '',
   region_type varchar(255) NOT NULL DEFAULT '' ,
   district_type varchar(255) NOT NULL DEFAULT '' ,
   offshore_region varchar(255) NOT NULL DEFAULT '',  
   unique(fips_code,state,county,land_class,land_category,offshore_region)
   )
