databaseChangeLog:
  - changeSet:
      id: refactor-production-fy-functions
      author: Jeff Schwartz
      changes:
      - sqlFile:
          path: src/functions/ignore_empty_production_fy.sql
          splitStatements: false
      - sqlFile:
          path: src/functions/insert_commodity_production_fy.sql
          splitStatements: false
      - sqlFile:
          path: src/functions/insert_location_production_fy.sql
          splitStatements: false
      - sqlFile:
          path: src/functions/insert_period_production_fy.sql
          splitStatements: false
      - sqlFile:
          path: src/functions/transform_county_state_fips_code_prod_fy.sql
          splitStatements: false
      - sqlFile:
          path: src/functions/transform_offshore_region_production.sql
          splitStatements: false
      - sqlFile:
          path: src/functions/transform_product.sql
          splitStatements: false
