--
-- PostgreSQL database dump
--

-- Dumped from database version 12.9 (Debian 12.9-1.pgdg110+1)
-- Dumped by pg_dump version 13.5 (Ubuntu 13.5-0ubuntu0.21.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: commodity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.commodity (
    commodity_id integer NOT NULL,
    mineral_lease_type character varying(255) DEFAULT ''::character varying NOT NULL,
    commodity character varying(255) DEFAULT ''::character varying NOT NULL,
    product character varying(255) DEFAULT ''::character varying NOT NULL,
    commodity_order character varying(5) DEFAULT ''::character varying NOT NULL
);


ALTER TABLE public.commodity OWNER TO postgres;

--
-- Name: commodity_commodity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.commodity ALTER COLUMN commodity_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.commodity_commodity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: commodity commodity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.commodity
    ADD CONSTRAINT commodity_pkey PRIMARY KEY (commodity_id);


--
-- Name: commodity commodity_unique_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.commodity
    ADD CONSTRAINT commodity_unique_key UNIQUE (mineral_lease_type, commodity, product);


--
-- PostgreSQL database dump complete
--

