--
-- PostgreSQL database dump
--

-- Dumped from database version 12.9 (Debian 12.9-1.pgdg110+1)
-- Dumped by pg_dump version 13.5 (Ubuntu 13.5-0ubuntu0.21.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: fund; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fund (
    fund_id integer NOT NULL,
    recipient character varying(255) DEFAULT ''::character varying NOT NULL,
    fund_class character varying(255) DEFAULT ''::character varying NOT NULL,
    fund_type character varying(255) DEFAULT ''::character varying NOT NULL,
    revenue_type character varying(255) DEFAULT ''::character varying NOT NULL,
    source character varying(255) DEFAULT ''::character varying NOT NULL,
    disbursement_type character varying(255) DEFAULT ''::character varying NOT NULL
);


ALTER TABLE public.fund OWNER TO postgres;

--
-- Name: fund_fund_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fund ALTER COLUMN fund_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fund_fund_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fund fund_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fund
    ADD CONSTRAINT fund_pkey PRIMARY KEY (fund_id);


--
-- Name: fund fund_unique_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fund
    ADD CONSTRAINT fund_unique_key UNIQUE (recipient, fund_class, fund_type, revenue_type, source, disbursement_type);


--
-- PostgreSQL database dump complete
--

