--
-- PostgreSQL database dump
--

-- Dumped from database version 12.9 (Debian 12.9-1.pgdg110+1)
-- Dumped by pg_dump version 13.5 (Ubuntu 13.5-0ubuntu0.21.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: period; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.period (
    period_id integer NOT NULL,
    period character varying(255) DEFAULT 'Monthly'::character varying,
    calendar_year integer NOT NULL,
    fiscal_year integer NOT NULL,
    month integer NOT NULL,
    month_long character varying(255) NOT NULL,
    month_short character varying(3) NOT NULL,
    fiscal_month integer NOT NULL,
    period_date date NOT NULL
);


ALTER TABLE public.period OWNER TO postgres;

--
-- Name: period_period_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.period ALTER COLUMN period_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.period_period_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: period period_period_calendar_year_fiscal_year_month_month_long_fi_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.period
    ADD CONSTRAINT period_period_calendar_year_fiscal_year_month_month_long_fi_key UNIQUE (period, calendar_year, fiscal_year, month, month_long, fiscal_month, period_date);


--
-- Name: period period_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.period
    ADD CONSTRAINT period_pkey PRIMARY KEY (period_id);


--
-- PostgreSQL database dump complete
--

