name: Apply database changes

on:
  workflow_call:
    inputs:
      cf-space:
        type: string
        default: dev
      cf-app-name:
        type: string
        required: true
      cf-service-name:
        type: string
        required: true

    secrets:
      CF_USERNAME:
        required: true

      CF_PASSWORD:
        required: true
    
jobs:
  check_database_changelog:
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.filter.outputs.changelog }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check if files changed
        uses: dorny/paths-filter@v3
        id: filter
        with: 
          filters: |
            changelog:
              - 'database/changelog/**'
  apply_database_updates:
    # needs: check_database_changelog
    # if: ${{ needs.check_database_changelog.outputs.changelog == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CF CLI
        uses: doi-onrr/oddd-actions/.github/actions/cf-install@v1

      - name: Log in to Cloud Foundry
        shell: bash
        run: |
          cf login -u ${{ secrets.CF_USERNAME }} -p ${{ secrets.CF_PASSWORD }} -a api.fr.cloud.gov -o doi-onrr -s ${{ inputs.cf-space }}

      - name: Install connect-to-service CF plugin
        shell: bash
        run: |
          cf install-plugin -f https://github.com/cloud-gov/cf-service-connect/releases/download/1.1.0/cf-service-connect-linux-amd64
      
      - name: Open the tunnel and capture tunnel info
        id: tunnel
        shell: bash
        run: |
          # Start the tunnel in the background and write output to a log file
          cf connect-to-service --no-client ${{ inputs.cf-app-name }} ${{ inputs.cf-service-name }} > tunnel.log 2>&1 &
          
          # Wait for the tunnel to open by checking for the "Port:" line in tunnel.log
          timeout=30
          while [ $timeout -gt 0 ]; do
            if grep -q "^Port:" tunnel.log; then
              break
            fi
            sleep 1
            timeout=$((timeout - 1))
          done

          if [ $timeout -le 0 ]; then
            echo "Tunnel did not open within the expected time." >&2
            exit 1
          fi

          # Now that the tunnel is open, capture the complete output from the log file
          output=$(cat tunnel.log)
          host=$(echo "$output" | grep "^Host:" | awk '{print $2}' | xargs)
          port=$(echo "$output" | grep "^Port:" | awk '{print $2}' | xargs)
          username=$(echo "$output" | grep "^Username:" | awk '{print $2}' | xargs)
          password=$(echo "$output" | grep "^Password:" | awk '{print $2}' | xargs)
          dbname=$(echo "$output" | grep "^Name:" | awk '{print $2}' | xargs)

          # Export the values as outputs for later steps
          echo "host=${host}" >> $GITHUB_OUTPUT
          echo "port=${port}" >> $GITHUB_OUTPUT
          echo "username=${username}" >> $GITHUB_OUTPUT
          echo "password=${password}" >> $GITHUB_OUTPUT
          echo "dbname=${dbname}" >> $GITHUB_OUTPUT

      - name: Apply Liquibase updates
        uses: liquibase-github-actions/update@v4.31.1
        with:
          changelogFile: ./database/changelog/changelog-root.yaml
          url: jdbc:postgresql://${{ steps.tunnel.outputs.host }}:${{ steps.tunnel.outputs.port }}/${{ steps.tunnel.outputs.dbname }}
          username: ${{ steps.tunnel.outputs.username }}
          password: ${{ steps.tunnel.outputs.passord }}