name: Apply database changes

on:
  workflow_call:
    inputs:
      cf-space:
        type: string
        default: dev
      cf-app-name:
        type: string
        required: true
      cf-service-name:
        type: string
        required: true

    secrets:
      CF_USERNAME:
        required: true

      CF_PASSWORD:
        required: true
    
jobs:
  check_database_changelog:
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.filter.outputs.changelog }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check if files changed
        uses: dorny/paths-filter@v3
        id: filter
        with: 
          filters: |
            changelog:
              - 'database/changelog/**'
  apply_database_updates:
    # needs: check_database_changelog
    # if: ${{ needs.check_database_changelog.outputs.changelog == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CF CLI
        uses: doi-onrr/oddd-actions/.github/actions/cf-install@v1

      - name: Log in to Cloud Foundry
        shell: bash
        run: |
          cf login -u ${{ secrets.CF_USERNAME }} -p ${{ secrets.CF_PASSWORD }} -a api.fr.cloud.gov -o doi-onrr -s ${{ inputs.cf-space }}

      - name: Install connect-to-service CF plugin
        shell: bash
        run: |
          cf install-plugin -f https://github.com/cloud-gov/cf-service-connect/releases/download/1.1.0/cf-service-connect-linux-amd64
      
      - name: Open tunnel and apply Liquibase updates
        shell: bash
        run: |
          # Start the tunnel in the background
          cf connect-to-service --no-client ${{ inputs.cf-app-name }} ${{ inputs.cf-service-name }} > tunnel.log 2>&1 &
          TUNNEL_PID=$!

          # Wait for tunnel to open
          timeout=30
          while [ $timeout -gt 0 ]; do
            if grep -q "^Port:" tunnel.log; then
              break
            fi
            sleep 1
            timeout=$((timeout - 1))
          done

          if [ $timeout -le 0 ]; then
            echo "Tunnel did not open in time."
            kill $TUNNEL_PID
            exit 1
          fi

          # Extract connection details
          output=$(cat tunnel.log)
          host=$(echo "$output" | grep "^Host:" | awk '{print $2}' | xargs)
          port=$(echo "$output" | grep "^Port:" | awk '{print $2}' | xargs)
          username=$(echo "$output" | grep "^Username:" | awk '{print $2}' | xargs)
          password=$(echo "$output" | grep "^Password:" | awk '{print $2}' | xargs)
          dbname=$(echo "$output" | grep "^Name:" | awk '{print $2}' | xargs)

          # Run Liquibase
          docker run --rm --network=host \
            -v "${PWD}/database/changelog:/liquibase/changelog" \
            liquibase/liquibase:4.31.1 \
            --changelog-file=./changelog-root.yaml \
            --url=jdbc:postgresql://${host}:${port}/${dbname} \
            --username=${username} \
            --password=${password} \
            update

          # Cleanup
          kill $TUNNEL_PID