name: Build and deploy

on:
  push:
    branches-ignore:
      - master
  
  pull_request:
    branches:
      - dev
      - master

jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      cf_db_space: ${{ steps.set-vars.outputs.cf_db_space }}
      cf_db_app_name: ${{ steps.set-vars.outputs.cf_db_app_name }}
      cf_db_service_name: ${{ steps.set-vars.outputs.cf_db_service_name }}
    steps:
      - name: Set Cloud Foundry variables for connecting to the db
        id: set-vars
        run: |
          branch="${GITHUB_REF##*/}"
          if [ "$branch" = "master" ]; then
            echo "cf_db_space=prod" >> $GITHUB_OUTPUT
            echo "cf_db_app_name=nrrd" >> $GITHUB_OUTPUT
            echo "cf_db_service_name=nrrd-a-psql" >> $GITHUB_OUTPUT
          elif [ "$branch" = "dev" ]; then
            echo "cf_db_space=prod" >> $GITHUB_OUTPUT
            echo "cf_db_app_name=hasura-dev" >> $GITHUB_OUTPUT
            echo "cf_db_service_name=nrrd-b-psql" >> $GITHUB_OUTPUT
          else
            echo "cf_db_space=dev" >> $GITHUB_OUTPUT
            echo "cf_db_app_name=hasura-sandbox" >> $GITHUB_OUTPUT
            echo "cf_db_service_name=nrrd-psql" >> $GITHUB_OUTPUT
          fi
  
  apply_database_updates:
    needs: set-vars
    uses: ./.github/workflows/apply-database-changes.yml
    with:
      cf-space: ${{ needs.set-vars.outputs.cf_db_space }}
      cf-app-name: ${{ needs.set-vars.outputs.cf_db_app_name }}
      cf-service-name: ${{ needs.set-vars.outputs.cf_db_service_name }}
    secrets: inherit

  generate_downloads:
    needs: [set-vars, apply_database_updates]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CF CLI
        uses: doi-onrr/oddd-actions/.github/actions/cf-install@v1

      - name: Log in to Cloud Foundry
        shell: bash
        run: |
          cf login -u ${{ secrets.CF_USERNAME }} -p ${{ secrets.CF_PASSWORD }} -a api.fr.cloud.gov -o doi-onrr -s ${{ needs.set-vars.outputs.cf_db_space }}

      - name: Install connect-to-service CF plugin
        shell: bash
        run: |
          cf install-plugin -f https://github.com/cloud-gov/cf-service-connect/releases/download/1.1.0/cf-service-connect-linux-amd64
      
      - name: Install gnumeric
        run: |
          sudo apt-get install --no-install-recommends -y gnumeric
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies in database directory
        run: npm install
        working-directory: ./database

      - name: Open tunnel and apply generate downloads
        run: .github/scripts/generate-downloads-via-cf-tunnel.sh
        shell: bash
        env:
          CF_APP_NAME: ${{ needs.set-vars.outputs.cf_db_app_name }}
          CF_SERVICE_NAME: ${{ needs.set-vars.outputs.cf_db_service_name }}

      - name: Upload download files
        uses: actions/upload-artifact@v4
        with:
          name: downloads
          path: /tmp/downloads

  # build:
  #   runs-on: ubuntu-latest
  #   env:
  #     GTM_ID: ${{ secrets.GTM_ID }}
  #   outputs:
  #     build-dir: ${{ steps.set-output.outputs.build-dir }}

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
    
  #   - name: Setup node
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: 20
  #       cache: 'npm'
    
  #   - name: Install dependencies
  #     run: npm ci
    
  #   - name: Build application
  #     run: npm run build --if-present

  #   - name: Rename ~partytown directory
  #     run: |
  #       if [ -d public/~partytown ]; then
  #         mv public/~partytown public/_partytown
  #       fi

  #   - name: Upload build artifacts
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: public
  #       path: public

  # preview:
  #   needs: build
  #   if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/dev'
  #   uses: doi-onrr/oddd-actions/.github/workflows/cf-deploy.yml@v1
  #   with:
  #     manifest: manifest.dev.yml
  #   secrets: inherit

  # dev:
  #   needs: build
  #   if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/dev'
  #   uses: doi-onrr/oddd-actions/.github/workflows/cf-deploy.yml@v1
  #   with:
  #     manifest: manifest.dev.yml
  #   secrets: inherit

  # prod:
  #   needs: build
  #   if: github.ref == 'refs/heads/master'
  #   uses: doi-onrr/oddd-actions/.github/workflows/cf-deploy.yml@v1
  #   with:
  #     cf-space: prod
  #     manifest: manifest.master.yml
  #   secrets: inherit