name: Build and deploy

on:
  push:
    branches-ignore:
      - master
  
  pull_request:
    branches:
      - dev
      - master

jobs:
  apply_database_updates:
    uses: doi-onrr/oddd-actions/.github/workflows/apply-database-changes.yml@v1
    with:
      cf-space: dev
      cf-app-name: hasura-sandbox
      cf-service-name: nrrd-psql
    secrets: inherit
