name: Check Links

on:
  schedule:
    - cron: '0 6 * * 0'  # 11 PM Mountain Standard Time (MST)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GATSBY_HASURA_URI: https://hasura-prod.app.cloud.gov/v1/graphql
      STAGE: ''
      BRANCH: 'master'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    - name: Build application
      run: npm run build --if-present

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: public
        path: public
  
  link-check:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: public
          path: public

      - name: Check links in built site
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --exclude-mail --no-progress ./public/**/*.html