databaseChangeLog:
  - changeSet:
      id: production-monthly-23-june-truncate
      author: Jeff Schwartz
      changes:
      - sql:
          dbms: 'postgresql'
          sql: |
            TRUNCATE TABLE monthly_production_elt
  - changeSet:
      id: production-monthly-23-june-load-csv
      author: Jeff Schwartz
      changes:
      - loadData:
          tableName: monthly_production_elt
          file: '../static/csv/production/monthly_production.csv'
          quotchar: '""'
          columns:
          - column:
              header: Production Date
              name: period_date
              type: STRING
          - column:
              header: Land Class
              name: land_class
          - column:
              header: Land Category
              name: land_category
          - column:
              header: Commodity
              name: commodity
          - column:
              header: Volume
              name: volume
  - changeSet:
      id: production-monthly-23-june-load-production
      author: Jeff Schwartz
      changes:
      - sql:
          dbms: 'postgresql'
          sql: |
            CALL load_production_monthly();